export { default as HomePage } from './HomePage/HomePage'
export { default as LandingPage } from './LandingPage/LandingPage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as SignUpPage } from './SignUpPage/SignUpPage'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
